### PR TITLE
Proposal: add a function to handle click

### LINKED ISSUE #56: Add `buffer.close_button_command` to resolve Nvim Tree `bdelete` issues.
I'd be ok with adding a `buffer.close_button_command` option that's set to `bdelete` by default but can be configured to `Bdelete` if the user wants to. Having `bufdelete.nvim` as a hard dependency for everyone is not acceptable.

_Originally posted by @noib3 in https://github.com/noib3/nvim-cokeline/issues/55#issuecomment-1086947224_

This is the best interim solution for Nvim-Tree issues. Open for PRs. 

Related #44

### LINKED ISSUE #66: Cannot close terminal tab
I cannot close terminal tab by clicking on "x" icon or by using pick close option.
Error is:
Error detected while processing function CokelineHandleCloseButtonClick:
line    2:
E89: term://~:/usr/bin/zsh will be killed (add ! to override)

I can close it by forcing it using :bd!

I took a look at this function:
    function! CokelineHandleCloseButtonClick(minwid, clicks, button, modifiers)
      if a:button != 'l' | return | endif
      execute printf('bdelete %s', a:minwid)
    endfunction
Is there a way to check if the tab is terminal and to use bdelete! for it, while keeping bdelete for other tabs?

### PR DESCRIPTION
**Pull request by aspeddro**
This makes the settings more customizable following the `cokeline` goal.

### Proposal

Introduce two options to handle with click

- `handle_click`
- `handle_click_component`

**Breaking**:

- rename `delete_buffer_on_left_click` to `click`, since user can handle click event on components

Close #66 
Close #56

### CODE REVIEW

**Comment by aspeddro** [comment]
Or a function to handler with click.

```lua
require('cokeline').setup{
  handler_click = function(minwid, clicks, button, modifiers)
  end
}
```

**Comment by willothy** [comment]
What's the status of this PR? This is definitely something I'd like to add if it's ready - I am a bit hesitant to merge breaking changes so soon after taking over as maintainer though, maybe `delete_buffer_on_left_click` could be kept in (for now) and essentially used as an alias for `click`, just to avoid breaking people's configs?

**Comment by aspeddro** [comment]
I'm not going to go ahead with this PR. Feel free to fork.

**Comment by willothy** [comment]
For sure, no worries!

**Pull request closed without merging**
